name: Run the tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    test:
        strategy:
          fail-fast: false
          matrix:
            shard: [1/4, 2/4, 3/4, 4/4]
        runs-on: ubuntu-latest

        steps:
          - name: Check out project
            uses: actions/checkout@v2

          - name: Install Node.js
            uses: actions/setup-node@v3
            with:
                node-version: '18'

          - name: Clean install the project
            run: npm ci

          - name: Install Playwright
            run: npx playwright install --with-deps

          - name: Run Playwright tests
            run: npx playwright test --grep-invert=@api --shard ${{ matrix.shard }}
          - uses: actions/upload-artifact@v3
            if: always()
            with:
                name: playwright-report
                path: playwright-report/
                retention-days: 30
          - name: Upload blob report to GitHub Actions Artifacts
            if: always()
            uses: actions/upload-artifact@v3
            with:
              name: all-blob-reports
              path: blob-report
              retention-days: 1
    merge-reports:
                # Merge reports after playwright-tests, even if some shards have failed
                if: always()
                needs: [test]
            
                runs-on: ubuntu-latest
                steps:
                - uses: actions/checkout@v3
                - uses: actions/setup-node@v3
                  with:
                    node-version: 18
                - name: Install dependencies
                  run: npm ci
            
                - name: Download blob reports from GitHub Actions Artifacts
                  uses: actions/download-artifact@v3
                  with:
                    name: all-blob-reports
                    path: all-blob-reports
            
                - name: Merge into HTML Report
                  run: npx playwright merge-reports --reporter html ./all-blob-reports 
            
                - name: Upload HTML report
                  uses: actions/upload-artifact@v3
                  with:
                    name: html-report--attempt-${{ github.run_attempt }}
                    path: playwright-report
                    retention-days: 14
